[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
libs = ["lib"]
cache_path = "forge-cache"
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
auto_detect_remappings = false
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true